github: [your_github_username, your_github_username2]
patreon: your_patreon_username
open_collective: your_open_collective_username
ko_fi: your_ko_fi_username
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: your_liberapay_username
issuehunt: your_issuehunt_username
otechie: your_otechie_username
custom: ['https://btc.com/1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ']